title = "J0219-06"

[Name]
value = "J0219-06"
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[RA]
value = "02:19:00" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[Dec]
value = "-06:10:00" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[DM]
value = 8.46 #pc/cm^3
error = 0.07
ref = "https://doi.org/10.1093/mnras/staf098"

[Period]
value = 1.87868 #s
error = 0.00004
ref = "https://doi.org/10.1093/mnras/staf098"

[Pepoch]
value = 59330.517875
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

#Turner et al. 2025: https://doi.org/10.1093/mnras/staf098
#MTP0021