title = "J0305+40"

[Name]
value = "J0305+40"
error = false
ref = "https://doi.org/10.1051/0004-6361/201833102"

[RA]
value = "03:05:26" #hh:mm:ss.ss
error = "00:00:32"
ref = "https://doi.org/10.1051/0004-6361/201833102"

[Dec]
value = "+40:01" #(sign)dd:mm:ss.ss
error = "00:15"
ref = "https://doi.org/10.1051/0004-6361/201833102"

[DM]
value = 24 #pc/cc
error = 2
ref = "https://doi.org/10.1051/0004-6361/201833102"

[Flux]

    [Flux.111]
  value = 2700 #mJy
  error = false
  frequency = 111 #MHz
  ref = "https://doi.org/10.1051/0004-6361/201833102"

[Width]

    [Width.111]
  value = 12.5 #ms
  error = false
  frequency = 111 #MHz
  ref = "https://doi.org/10.1051/0004-6361/201833102"

#Tyul'bashev+18b: https://doi.org/10.1051/0004-6361/201833102
