title = "J0402-6542"

[Name]
value = "J0402-6542"
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[RA]
value = "04:02:52.27" #hh:mm:ss.ss
error = "00:00:00.03"
ref = "https://doi.org/10.1093/mnras/staf098"

[Dec]
value = "-65:42:43.41" #(sign)dd:mm:ss.ss
error = "00:00:00.16"
ref = "https://doi.org/10.1093/mnras/staf098"

[DM]
value = 31.5 #pc/cm^3
error = 0.2
ref = "https://doi.org/10.1093/mnras/staf098"

[Period]
value = 3.03352298461 #s
error = 0.00000000007
ref = "https://doi.org/10.1093/mnras/staf098"

[Pdot]
value = 5.601e-15
error = 0.002e-15
ref = "https://doi.org/10.1093/mnras/staf098"

[Pepoch]
value = 59581.5
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

#Turner et al. 2025: https://doi.org/10.1093/mnras/staf098
#MTP0017