title = "J0440+35"

[Name]
value = "J0440+35"
error = false
ref = "https://doi.org/10.1051/0004-6361/202449762"

[RA]
value = "04:40:00" #hh:mm:ss.ss
error = "00:00:90"
ref = "https://doi.org/10.1051/0004-6361/202449762"

[Dec]
value = "+35:22" #(sign)dd:mm:ss.ss
error = "00:15"
ref = "https://doi.org/10.1051/0004-6361/202449762"

[Period]
value = 2.23
error = false
ref = "https://doi.org/10.1051/0004-6361/202449762"

[DM]
value =  2.6 #pc/cc
error = 1.0
ref = "https://doi.org/10.1051/0004-6361/202449762"

[Flux]

    [Flux.110]
  value = 14000 #mJy 
  frequency = 110.25 #MHz
  error = false
  ref = "https://doi.org/10.1051/0004-6361/202449762"

[Width]

    [Width.110]
  value = 21 #ms
  frequency = 110.25 #MHz
  error = false
  ref = "https://doi.org/10.1051/0004-6361/202449762"

Tyul'bashev et al. 2024: https://doi.org/10.1051/0004-6361/202449762