title = "J0639+0828"

[Name]
value = "J0639+0828"
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[RA]
value = "06:39:53.0" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[Dec]
value = "+08:28" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[DM]
value =  290.1 #pc/cc
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"


#Han et al. 2025: https://doi.org/10.1088/1674-4527/ada3b7