title = "J0917-4245"

[Name]
value = "J0917-4245"
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[RA]
value = "09:17:28.3" #hh:mm:ss.ss
error = "00:00:00.1"
ref = "https://doi.org/10.1093/mnras/staf098"

[Dec]
value = "-42:45:55" #(sign)dd:mm:ss.ss
error = "00:00:01"
ref = "https://doi.org/10.1093/mnras/staf098"

[DM]
value = 97.7 #pc/cm^3
error = 0.3
ref = "https://doi.org/10.1093/mnras/staf098"

[Period]
value = 2.5519 #s
error = 0.0001
ref = "https://doi.org/10.1093/mnras/staf098"

[Pepoch]
value = 59699.588283
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

#Turner et al. 2025: https://doi.org/10.1093/mnras/staf098
#MTP0031