title = "J0933-4604"

[Name]
value = "J0933-4604"
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[RA]
value = "09:33:53.2" #hh:mm:ss.ss
error = "00:00:00.1"
ref = "https://doi.org/10.1093/mnras/staf1827"

[Dec]
value = "-46:04:57" #(sign)dd:mm:ss.ss
error = "00:00:01"
ref = "https://doi.org/10.1093/mnras/staf1827"

[DM]
value = 120.8 #pc/cm^3
error = 0.1
ref = "https://doi.org/10.1093/mnras/staf1827"

[Period]
value = 3.66981
error = 0.00006
ref = "https://doi.org/10.1093/mnras/staf1827"

[Pepoch]
value = 59782.391977
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

#Tian et al. 2025: https://doi.org/10.1093/mnras/staf1827
#MTP0067