title = "J0941+16"

[Name]
value = "J0941+16"
error = false
ref = "https://doi.org/10.1051/0004-6361/201833102"

[RA]
value = "09:41:30" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1051/0004-6361/201833102"

[Dec]
value = "+16:21" #(sign)dd:mm:ss.ss
error = "00:20"
ref = "https://doi.org/10.1051/0004-6361/201833102"

[DM]
value = 23 #pc/cc
error = 2
ref = "https://doi.org/10.1051/0004-6361/201833102"


#Tyul'bashev+18b: https://doi.org/10.1051/0004-6361/201833102
