title = "J1005+30"

[Name]
value = "J1005+30"
error = false
ref = "https://doi.org/10.1134/S1063772918010079"

[RA]
value = "10:05:30" #hh:mm:ss.ss
error = "00:00:40"
ref = "https://doi.org/10.1051/0004-6361/201833102"

[Dec]
value = "+30:15" #(sign)dd:mm:ss.ss
error = "00:15"
ref = "https://doi.org/10.1051/0004-6361/201833102"

[DM]
value = 17.5 #pc/cc
error = 1.5
ref = "https://doi.org/10.1051/0004-6361/201833102"

[Flux]

    [Flux.111]
  value = 28300 #mJy
  error = false
  frequency = 111 #MHz
  ref = "https://doi.org/10.1051/0004-6361/201833102"

[Width]

    [Width.111]
  value = 30 #ms
  error = false
  frequency = 111 #MHz
  ref = "https://doi.org/10.1051/0004-6361/201833102"

#References go here
#Tyul'bashev+18a: https://doi.org/10.1134/S1063772918010079
#Tyul'bashev+18b: https://doi.org/10.1051/0004-6361/201833102
