title = "J1243-0435"

[Name]
value = "J1243-0435"
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[RA]
value = "12:43:23" #hh:mm:ss.ss
error = "00:00:02"
ref = "https://doi.org/10.1093/mnras/staf1827"

[Dec]
value = "-04:35:36" #(sign)dd:mm:ss.ss
error = "00:00:26"
ref = "https://doi.org/10.1093/mnras/staf1827"

[DM]
value = 12.0 #pc/cm^3
error = 0.1
ref = "https://doi.org/10.1093/mnras/staf1827"

[Period]
value = 4.86772
error = 0.00002
ref = "https://doi.org/10.1093/mnras/staf1827"

[Pepoch]
value = 59823.512112
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

#Tian et al. 2025: https://doi.org/10.1093/mnras/staf1827
#MTP0068