title = "J1308-61"

[Name]
value = "J1308-61"
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[RA]
value = "13:08:59" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[Dec]
value = "-61:17:00" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[DM]
value = 224.5 #pc/cm^3
error = 0.2
ref = "https://doi.org/10.1093/mnras/staf098"

[Period]
value = 3.9548 #s
error = 0.0003
ref = "https://doi.org/10.1093/mnras/staf098"

[Pepoch]
value = 59513.543146
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

#Turner et al. 2025: https://doi.org/10.1093/mnras/staf098
#MTP0035