title = "J1319-4536"

[Name]
value = "J1319-4536"
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[RA]
value = "13:19:48.31" #hh:mm:ss.ss
error = "00:00:00.06"
ref = "https://doi.org/10.1093/mnras/staf098"

[Dec]
value = "-45:36:03.0" #(sign)dd:mm:ss.ss
error = "00:00:00.8"
ref = "https://doi.org/10.1093/mnras/staf098"

[DM]
value = 40.41 #pc/cm^3
error = 0.08
ref = "https://doi.org/10.1093/mnras/staf098"

[Period]
value = 1.8709058202 #s
error = 0.0000000002
ref = "https://doi.org/10.1093/mnras/staf098"

[Pdot]
value = 6.975e-15
error = 0.003e-15
ref = "https://doi.org/10.1093/mnras/staf098"

[Pepoch]
value = 59369
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

#Turner et al. 2025: https://doi.org/10.1093/mnras/staf098
#MTP0023