title = "J1336+33"

[Name]
value = "J1336+33"
error = false
ref = "https://doi.org/10.1134/S1063772918010079"

[RA]
value = "13:36:26" #hh:mm:ss.ss
error = "00:00:50"
ref = "https://doi.org/10.1051/0004-6361/201833102"

[Dec]
value = "+33:46" #(sign)dd:mm:ss.ss
error = "00:15"
ref = "https://doi.org/10.1051/0004-6361/201833102"

[DM]
value = 8 #pc/cc
error = 1
ref = "https://doi.org/10.1051/0004-6361/201833102"

[Period]
value = 3.013
error = 0.003
ref = "https://doi.org/10.1051/0004-6361/201833102"

[Flux]

    [Flux.111]
  value = 8400 #mJy
  error = false
  frequency = 111 #MHz
  ref = "https://doi.org/10.1051/0004-6361/201833102"

[Width]

    [Width.111]
  value = 15 #ms
  error = false
  frequency = 111 #MHz
  ref = "https://doi.org/10.1051/0004-6361/201833102"

#Tyul'bashev+18a: https://doi.org/10.1134/S1063772918010079
#Tyul'bashev+18b: https://doi.org/10.1051/0004-6361/201833102
