title = "J1354+2453"

[Name]
value = "J1354+2453"
error = false
ref = "https://doi.org/10.1088/0004-637X/809/1/67"

[RA]
value = "13:54:13.383" #hh:mm:ss.ss
error = "00:00:00.003"
ref = "https://doi.org/10.3847/1538-4357/ad11f0"

[Dec]
value = "+24:53:46.16" #(sign)dd:mm:ss.ss
error = "00:00:00.06"
ref = "https://doi.org/10.3847/1538-4357/ad11f0"

[DM]
value = 20.0 #pc/cc
error = 0.2
ref = "https://doi.org/10.3847/1538-4357/ad11f0"

[Period]
value = 0.851063907874 #s
error = 0.000000000006
ref = "https://doi.org/10.3847/1538-4357/ad11f0"

[Pepoch]
value = 58521
error = false
ref = "https://doi.org/10.3847/1538-4357/ad11f0"

[Pdot]
value = 1.4007e-16 
error = 0.0007e-16
ref = "https://doi.org/10.3847/1538-4357/ad11f0"

[Flux]

    [Flux.350]
  value = 100  #mJy 
  frequency = 350 #MHz
  error = false
  ref = "https://doi.org/10.1088/0004-637X/809/1/67"


#Karako-Argaman et al 2015: https://doi.org/10.1088/0004-637X/809/1/67
#McEwen et al. 2024: https://doi.org/10.3847/1538-4357/ad11f0 
