title = "J1502+28"

[Name]
value = "J1502+28"
error = false
ref = "https://doi.org/10.1051/0004-6361/201833102"

[RA]
value = "15:02:09" #hh:mm:ss.ss
error = "00:00:40"
ref = "https://doi.org/10.1051/0004-6361/201833102"

[Dec]
value = "+28:13" #(sign)dd:mm:ss.ss
error = "00:15"
ref = "https://doi.org/10.1051/0004-6361/201833102"

[DM]
value = 14 #pc/cc
error = 1.5
ref = "https://doi.org/10.1051/0004-6361/201833102"

[Period]
value = 3.784
error = 0.003
ref = "https://doi.org/10.1051/0004-6361/201833102"

[Flux]

    [Flux.111]
  value = 16300 #mJy
  error = false
  frequency = 111 #MHz
  ref = "https://doi.org/10.1051/0004-6361/201833102"

[Width]

    [Width.111]
  value = 25 #ms
  error = false
  frequency = 111 #MHz
  ref = "https://doi.org/10.1051/0004-6361/201833102"

#Tyul'bashev+18b: https://doi.org/10.1051/0004-6361/201833102
