title = "J1533-5609"

[Name]
value = "J1533-5609"
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[RA]
value = "15:33:50.46" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[Dec]
value = "-56:09:29.7" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[DM]
value = 95.31 #pc/cm^3
error = 0.09
ref = "https://doi.org/10.1093/mnras/staf098"

[Period]
value = 1.06167 #s
error = 0.00001
ref = "https://doi.org/10.1093/mnras/staf098"

[Pepoch]
value = 59568.370608
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

#Turner et al. 2025: https://doi.org/10.1093/mnras/staf098
#MTP0039