title = "J1548-5229"

[Name]
value = "J1548-5229"
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[RA]
value = "15:48:52.8" #hh:mm:ss.ss
error = "00:00:00.7"
ref = "https://doi.org/10.1093/mnras/staf1827"

[Dec]
value = "-52:29:07" #(sign)dd:mm:ss.ss
error = "00:00:06"
ref = "https://doi.org/10.1093/mnras/staf1827"

[DM]
value = 366.0 #pc/cm^3
error = 0.5
ref = "https://doi.org/10.1093/mnras/staf1827"

[Period]
value = 4.85
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[Pepoch]
value = 60646.374716
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

#Tian et al. 2025: https://doi.org/10.1093/mnras/staf1827
#MTP0069