title = "J1605-07"

[Name]
value = "J1605-07"
error = false
ref = "https://doi.org/10.1051/0004-6361/202449762"

[RA]
value = "16:05:12" #hh:mm:ss.ss
error = "00:00:90"
ref = "https://doi.org/10.1051/0004-6361/202449762"

[Dec]
value = "-07:37" #(sign)dd:mm:ss.ss
error = "00:15"
ref = "https://doi.org/10.1051/0004-6361/202449762"

[Period]
value = 1.81
error = false
ref = "https://doi.org/10.1051/0004-6361/202449762"

[DM]
value = 4.8 #pc/cc
error = 1.0
ref = "https://doi.org/10.1051/0004-6361/202449762"

[Flux]

    [Flux.110]
  value = 54000 #mJy 
  frequency = 110.25 #MHz
  error = false
  ref = "https://doi.org/10.1051/0004-6361/202449762"

[Width]

    [Width.110]
  value = 25 #ms
  frequency = 110.25 #MHz
  error = false
  ref = "https://doi.org/10.1051/0004-6361/202449762"

#Tyul'bashev et al. 2024: https://doi.org/10.1051/0004-6361/202449762