title = "J1637-53"

[Name]
value = "J1637-53"
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[RA]
value = "16:37:09" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[Dec]
value = "-53:26:11" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[DM]
value = 296 #pc/cm^3
error = 2
ref = "https://doi.org/10.1093/mnras/staf1827"

#Tian et al. 2025: https://doi.org/10.1093/mnras/staf1827
#MTP0052