title = "J1641-51"

[Name]
value = "J1641-51"
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[RA]
value = "16:41:39.43" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[Dec]
value = "-51:09:00.8" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[DM]
value = 250.4 #pc/cm^3
error = 0.7
ref = "https://doi.org/10.1093/mnras/staf098"

[Period]
value = 5.5143 #s
error = 0.0005
ref = "https://doi.org/10.1093/mnras/staf098"

[Pepoch]
value = 59495.789312
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

#Turner et al. 2025: https://doi.org/10.1093/mnras/staf098
#MTP0042