title = "J1647-41"

[Name]
value = "J1647-41"
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[RA]
value = "16:47:30" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[Dec]
value = "-41:17:18" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[DM]
value = 35.7 #pc/cm^3
error = 0.3
ref = "https://doi.org/10.1093/mnras/staf1827"

#Tian et al. 2025: https://doi.org/10.1093/mnras/staf1827
#MTP0061