title = "J1808-36"

[Name]
value = "J1808-36"
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[RA]
value = "18:08:27.65" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[Dec]
value = "-36:58:43.9" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[DM]
value = 41.0 #pc/cm^3
error = 0.5
ref = "https://doi.org/10.1093/mnras/staf098"

#Turner et al. 2025: https://doi.org/10.1093/mnras/staf098
#MTP0024