title = "J1807-11"

[Name]
value = "J1807-11"
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[RA]
value = "18:07:10.36" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[Dec]
value = "-11:51:08.2" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[DM]
value = 152.4 #pc/cm^3
error = 0.4
ref = "https://doi.org/10.1093/mnras/staf098"

#Turner et al. 2025: https://doi.org/10.1093/mnras/staf098
#MTP0047