title = "J1816-2419"

[Name]
value = "J1816-2419"
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[RA]
value = "18:16:39.6" #hh:mm:ss.ss
error = "00:00:00.1"
ref = "https://doi.org/10.1093/mnras/staf1827"

[Dec]
value = "-24:19:01" #(sign)dd:mm:ss.ss
error = "00:00:01"
ref = "https://doi.org/10.1093/mnras/staf1827"

[DM]
value = 269.4 #pc/cm^3
error = 0.7
ref = "https://doi.org/10.1093/mnras/staf1827"

[Period]
value = 4.612833
error = 0.000008
ref = "https://doi.org/10.1093/mnras/staf1827"

[Pepoch]
value = 59721.920209
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

#Tian et al. 2025: https://doi.org/10.1093/mnras/staf1827
#MTP0079