title = "J1828-0003"

[Name]
value = "J1828-0003"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "18:28:53" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "-00:03" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 193 #pc/cc
error = 3
ref = "https://doi.org/10.1088/1674-4527/accc76"
