title = "J1828-0003"

[Name]
value = "J1828-0003"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "18:28:44" #hh:mm:ss.ss
error = "00:20"
ref = "https://doi.org/10.3847/1538-4357/ad0eca"

[Dec]
value = "-00:03" #(sign)dd:mm:ss.ss
error = "00:02"
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 193 #pc/cc
error = 3
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 3.8071 #s
error = 0.0001
ref = "https://doi.org/10.3847/1538-4357/ad0eca"

#Zhou et al. 2023: https://doi.org/10.1088/1674-4527/accc76
#Zhi et al. 2024: https://doi.org/10.3847/1538-4357/ad0eca