title = "J1833+0050"

[Name]
value = "J1833+0050"
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[RA]
value = "18:33:56.3" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[Dec]
value = "+00:50" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[DM]
value =  190.9 #pc/cc
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[Period]
value = 0.90370 #s
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"


#Han et al. 2025: https://doi.org/10.1088/1674-4527/ada3b7