title = "J1836-0011"

[Name]
value = "J1836-0011"
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[RA]
value = "18:36:09.5" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[Dec]
value = "-00:11" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[DM]
value =  237.5 #pc/cc
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[Period]
value = 0.93960
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

#Han et al. 2025: https://doi.org/10.1088/1674-4527/ada3b7