title = "J1840-0809"

[Name]
value = "J1840-0809"
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[RA]
value = "18:40:33" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[Dec]
value = "-08:09:03" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[DM]
value = 300.0 #pc/cm^3
error = 0.4
ref = "https://doi.org/10.1093/mnras/staf1827"

[Period]
value = 0.1211853
error = 0.0000002
ref = "https://doi.org/10.1093/mnras/staf1827"

[Pepoch]
value = 60218.696604
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

#Tian et al. 2025: https://doi.org/10.1093/mnras/staf1827
#MTP0077