title = "J1843+0527"

[Name]
value = "J1843+0527"
error = false
ref = "https://palfa.nanograv.org/"

[RA]
value = "18:43:44" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "+05:27" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 261.1 #pc/cm^3
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 2.034918 #s
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Width]

    [Width.1250]
  value = 24.8 #ms
  frequency = 1250 #MHz
  error = false
  ref = "https://doi.org/10.1088/1674-4527/accc76"

#Zhou et al. 2023: https://doi.org/10.1088/1674-4527/accc76