title = "J1841-04"

[Name]
value = "J1841-04"
error = false
ref = "https://doi.org/10.1051/0004-6361/201833102"

[RA]
value = "18:41:10" #hh:mm:ss.ss
error = "00:00:20"
ref = "https://doi.org/10.1051/0004-6361/201833102"

[Dec]
value = "-04:48" #(sign)dd:mm:ss.ss
error = "00:25"
ref = "https://doi.org/10.1051/0004-6361/201833102"

[DM]
value = 29 #pc/cc
error = 3
ref = "https://doi.org/10.1051/0004-6361/201833102"

[Flux]

    [Flux.111]
  value = 3800 #mJy
  error = false
  frequency = 111 #MHz
  ref = "https://doi.org/10.1051/0004-6361/201833102"

[Width]

    [Width.111]
  value = 15 #ms
  error = false
  frequency = 111 #MHz
  ref = "https://doi.org/10.1051/0004-6361/201833102"

#Tyul'bashev+18b: https://doi.org/10.1051/0004-6361/201833102
