title = "J1843+01"

[Name]
value = "J1843+01"
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[RA]
value = "18:43:28" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/21/5/107"

[Dec]
value = "+01:19" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/21/5/107"

[DM]
value = 247.8 #pc/cc
error = 2.4
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Period]
value = 1.26702 #seconds
error = 0.00004
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Flux]

    [Flux.1400]
  value = 21 #mJy
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Width]

    [Width.1400]
  value = 3.5 #ms
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.3847/1538-4357/aaee65"


#Patel et al 2018: https://doi.org/10.3847/1538-4357/aaee65
#Han et al 2021: https://doi.org/10.1088/1674-4527/21/5/107
