title = "J1849+0619"

[Name]
value = "J1849+0619"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "18:49:35" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "+06:19" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 110 #pc/cc
error = 1
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 2.01123 #seconds
error = 3e-06
ref = "https://doi.org/10.1088/1674-4527/accc76"