title = "J1843-0051"

[Name]
value = "J1843-0051"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "18:43:32" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "-00:51" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 573 #pc/cc
error = 3
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 0.58 #seconds
error = 0.001
ref = "https://doi.org/10.1088/1674-4527/accc76"