title = "J1840-0245"

[Name]
value = "J1840-0245"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "18:40:14" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "-02:45" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 277 #pc/cc
error = 2
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 1.502 #seconds
error = 0.001
ref = "https://doi.org/10.1088/1674-4527/accc76"