title = "J1845-0008"

[Name]
value = "J1845-0008"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "18:45:08" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "-00:08" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 143 #pc/cc
error = 3
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 1.268 #seconds
error = 0.003
ref = "https://doi.org/10.1088/1674-4527/accc76"