title = "J1858+0453"

[Name]
value = "J1858+0453"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "18:58:48" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "+04:53" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 429 #pc/cc
error = 1
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 3.761 #seconds
error = 0.004
ref = "https://doi.org/10.1088/1674-4527/accc76"