title = "J1855-0211"

[Name]
value = "J1855-0211"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "18:55:32" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "-02:11" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 304 #pc/cc
error = 3
ref = "https://doi.org/10.1088/1674-4527/accc76"
