title = "J1856+0029"

[Name]
value = "J1856+0029"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "18:56:49" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "+00:29" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 234 #pc/cc
error = 3
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 0.376 #seconds
error = 0.003
ref = "https://doi.org/10.1088/1674-4527/accc76"