title = "J1855-0154"

[Name]
value = "J1855-0154"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "18:55:09" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "-01:54" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 417 #pc/cc
error = 1
ref = "https://doi.org/10.1088/1674-4527/accc76"
