title = "J1853+04"

[Name]
value = "J1853+04"
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[RA]
value = "18:53:46" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/21/5/107"

[Dec]
value = "+04:27" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/21/5/107"

[DM]
value = 549.3 #pc/cc
error = 1.3
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Period]
value = 1.32065 #seconds
error = 0.00004
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Flux]

    [Flux.1400]
  value = 33 #mJy
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Width]

    [Width.1400]
  value = 2.0 #ms
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.3847/1538-4357/aaee65"


#Patel et al 2018: https://doi.org/10.3847/1538-4357/aaee65
#Han et al 2021: https://doi.org/10.1088/1674-4527/21/5/107
