title = "J1906+0310"

[Name]
value = "J1906+0310"
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[RA]
value = "19:06:20.0" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[Dec]
value = "+03:10" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[DM]
value =  307.5 #pc/cc
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"


#Han et al. 2025: https://doi.org/10.1088/1674-4527/ada3b7