title = "J1900-0152"

[Name]
value = "J1900-0152"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "19:00:56" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "-01:52" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 314 #pc/cc
error = 2
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 1.384 #seconds
error = 0.006
ref = "https://doi.org/10.1088/1674-4527/accc76"