title = "J1904+0100"

[Name]
value = "J1904+0100"
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[RA]
value = "19:04:07.6" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[Dec]
value = "+01:00" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[DM]
value =  146.3 #pc/cc
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[Period]
value = 1.30879
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

#Han et al. 2025: https://doi.org/10.1088/1674-4527/ada3b7