title = "J1905+0558"

[Name]
value = "J1905+0558"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "19:05:04" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "+05:58" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 472 #pc/cc
error = 1
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 0.846 #seconds
error = 0.002
ref = "https://doi.org/10.1088/1674-4527/accc76"