title = "J1907+0555"

[Name]
value = "J1907+0555"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "19:07:27" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "+05:55" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 150 #pc/cc
error = 5
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 3.159 #seconds
error = 0.001
ref = "https://doi.org/10.1088/1674-4527/accc76"