title = "J1905+0156"

[Name]
value = "J1905+0156"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "19:05:08" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "+01:56" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 137 #pc/cc
error = 1
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 1.085 #seconds
error = 0.001
ref = "https://doi.org/10.1088/1674-4527/accc76"