title = "J1905+0414"

[Name]
value = "J1905+0414"
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[RA]
value = "19:05:11" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "+04:14" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.3847/1538-4357/aaee65"

[DM]
value = 383.0 #pc/cc
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 0.894124 #s
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Flux]

    [Flux.1400]
  value = 36 #mJy
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.3847/1538-4357/aaee65"

[Width]

    [Width.1400]
  value = 3.3 #ms
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.3847/1538-4357/aaee65"


#Deneva et al 2018: https://doi.org/10.3847/1538-4357/aaee65
