title = "J1900+0732"

[Name]
value = "J1900+0732"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "19:00:15" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "+07:32" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 226 #pc/cc
error = 1
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 1.709 #seconds
error = 0.001
ref = "https://doi.org/10.1088/1674-4527/accc76"