title = "J1919+1113"

[Name]
value = "J1919+1113"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "19:19:27" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "+11:13" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 288 #pc/cc
error = 2
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 0.766 #seconds
error = 0.005
ref = "https://doi.org/10.1088/1674-4527/accc76"