title = "J1918+1514"

[Name]
value = "J1918+1514"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "19:18:57" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "+15:14" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 134 #pc/cc
error = 2
ref = "https://doi.org/10.1088/1674-4527/accc76"
