title = "J1911+1440"

[Name]
value = "J1911+1440"
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[RA]
value = "19:11:20.9" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[Dec]
value = "+14:40" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[DM]
value =  87.2 #pc/cc
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[Period]
value = 0.58247 #s
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"


#Han et al. 2025: https://doi.org/10.1088/1674-4527/ada3b7