title = "J1914+0218"

[Name]
value = "J1914+0218"
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[RA]
value = "19:14:46" #hh:mm:ss.ss
error = "00:00:02"
ref = "https://doi.org/10.1093/mnras/staf1827"

[Dec]
value = "+02:18:13" #(sign)dd:mm:ss.ss
error = "00:00:30"
ref = "https://doi.org/10.1093/mnras/staf1827"

[DM]
value = 161 #pc/cm^3
error = 1
ref = "https://doi.org/10.1093/mnras/staf1827"

[Period]
value = 2.02
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[Pepoch]
value = 60292.481327
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

#Tian et al. 2025: https://doi.org/10.1093/mnras/staf1827
#MTP0078