title = "J1914+1053"

[Name]
value = "J1914+1053"
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[RA]
value = "19:14:15.8" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[Dec]
value = "+10:53" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[DM]
value =  108.0 #pc/cc
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"


#Han et al. 2025: https://doi.org/10.1088/1674-4527/ada3b7