title = "J1914+0219"

[Name]
value = "J1914+0219"
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[RA]
value = "19:14:53.5" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[Dec]
value = "+02:19" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[DM]
value =  161.4 #pc/cc
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[Period]
value = 2.01819
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

#Han et al. 2025: https://doi.org/10.1088/1674-4527/ada3b7