title = "J1911+1017"

[Name]
value = "J1911+1017"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "19:11:12" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "+10:17" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 162 #pc/cc
error = 2
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 1.337 #seconds
error = 0.001
ref = "https://doi.org/10.1088/1674-4527/accc76"