title = "J1921+0851"

[Name]
value = "J1921+0851"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "19:21:11" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "+08:51" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 101 #pc/cc
error = 2
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 0.957 #seconds
error = 0.005
ref = "https://doi.org/10.1088/1674-4527/accc76"