title = "J1935+1901"

[Name]
value = "J1935+1901"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "19:35:50" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "+19:01" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 365 #pc/cc
error = 2
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 0.897 #seconds
error = 0.001
ref = "https://doi.org/10.1088/1674-4527/accc76"