title = "J1948+2438"

[Name]
value = "J1948+2438"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "19:48:23" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "+24:38" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 450 #pc/cc
error = 4
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 1.9031 #seconds
error = 0.0002
ref = "https://doi.org/10.1088/1674-4527/accc76"