title = "J1940+2203"

[Name]
value = "J1940+2203"
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[RA]
value = "19:40:49" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "+22:03" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 59 #pc/cc
error = 9
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 11.906 #seconds
error = 0.001
ref = "https://doi.org/10.1088/1674-4527/accc76"