title = "J1945+2357"

[Name]
value = "J1945+2357"
error = false
ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

[RA]
value = "19:45:48" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Dec]
value = "+23:57" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[DM]
value = 87.5 #pc/cc
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Period]
value = 4.717624 #seconds
error = false
ref = "https://doi.org/10.1088/1674-4527/accc76"

[Flux]

    [Flux.1400]
  value = 101 #mJy
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

[Width]

    [Width.1400]
  value = 4 #ms
  error = false
  frequency = 1400 #MHz
  ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

[BurstRate]

    [BurstRate.Discovery]
  value= 54 #hour^-1
  error= false
  frequency= 1400 #MHz
  telescope= "Arecibo"
  minflux= 16 #mJy
  ref = "https://doi.org/10.1088/0004-637X/703/2/2259"

#Deneva et al 2009: https://doi.org/10.1088/0004-637X/703/2/2259
