title = "J1953-6112"

[Name]
value = "J1953-6112"
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[RA]
value = "19:53:07" #hh:mm:ss.ss
error = "00:00:02"
ref = "https://doi.org/10.1093/mnras/staf1827"

[Dec]
value = "-61:12:01" #(sign)dd:mm:ss.ss
error = "00:00:07"
ref = "https://doi.org/10.1093/mnras/staf1827"

[DM]
value = 43.0 #pc/cm^3
error = 0.1
ref = "https://doi.org/10.1093/mnras/staf1827"

[Period]
value = 0.46071448
error = 0.00000003
ref = "https://doi.org/10.1093/mnras/staf1827"

[Pepoch]
value = 60607.913720
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

#Tian et al. 2025: https://doi.org/10.1093/mnras/staf1827
#MTP0060