title = "J1951+2329"

[Name]
value = "J1951+2329"
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[RA]
value = "19:51:01.4" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[Dec]
value = "+23:29" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[DM]
value =  260.0 #pc/cc
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

[Period]
value = 1.82610
error = false
ref = "https://doi.org/10.1088/1674-4527/ada3b7"

#Han et al. 2025: https://doi.org/10.1088/1674-4527/ada3b7