title = "J2218-1229"

[Name]
value = "J2218-1229"
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[RA]
value = "22:18:44" #hh:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[Dec]
value = "-12:29:13" #(sign)dd:mm:ss.ss
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[DM]
value = 26.8 #pc/cm^3
error = 0.6
ref = "https://doi.org/10.1093/mnras/staf1827"

[Period]
value = 0.1627363
error = 0.0000001
ref = "https://doi.org/10.1093/mnras/staf1827"

[Pepoch]
value = 59673.192548
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

#Tian et al. 2025: https://doi.org/10.1093/mnras/staf1827
#MTP0058