title = "J2218+2902"

[Name]
value = "J2218+2902"
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

[RA]
value = "22:18:23.3" #hh:mm:ss.ss
error = "00:00:00.19"
ref = "https://doi.org/10.1093/mnras/staf098"

[Dec]
value = "+29:02:56" #(sign)dd:mm:ss.ss
error = "00:00:33"
ref = "https://doi.org/10.1093/mnras/staf098"

[DM]
value = 55.8 #pc/cm^3
error = 0.4
ref = "https://doi.org/10.1093/mnras/staf098"

[Period]
value = 17.49487 #s
error = 0.000003
ref = "https://doi.org/10.1093/mnras/staf098"

[Pepoch]
value = 59581.575764
error = false
ref = "https://doi.org/10.1093/mnras/staf098"

#Turner et al. 2025: https://doi.org/10.1093/mnras/staf098
#MTP0044