title = "J2317-4746"

[Name]
value = "J2317-4746"
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

[RA]
value = "23:17:28" #hh:mm:ss.ss
error = "00:00:02"
ref = "https://doi.org/10.1093/mnras/staf1827"

[Dec]
value = "-47:46:53" #(sign)dd:mm:ss.ss
error = "00:00:25"
ref = "https://doi.org/10.1093/mnras/staf1827"

[DM]
value = 15.9 #pc/cm^3
error = 0.3
ref = "https://doi.org/10.1093/mnras/staf1827"

[Period]
value = 1.7331602
error = 0.0000008
ref = "https://doi.org/10.1093/mnras/staf1827"

[Pepoch]
value = 59653.481429
error = false
ref = "https://doi.org/10.1093/mnras/staf1827"

#Tian et al. 2025: https://doi.org/10.1093/mnras/staf1827
#MTP0057