title = "J2337-04"
[Name]
value = "J2337-04"
error = false
ref = "https://doi.org/10.1051/0004-6361/202449762"

[RA]
value = "23:37:03" #hh:mm:ss.ss
error = "00:00:90"
ref = "https://doi.org/10.1051/0004-6361/202449762"

[Dec]
value = "-04:40" #(sign)dd:mm:ss.ss
error = "00:15"
ref = "https://doi.org/10.1051/0004-6361/202449762"

[DM]
value = 15.3 #pc/cc
error = 1.5
ref = "https://doi.org/10.1051/0004-6361/202449762"

[Flux]

    [Flux.110]
  value = 10000 #mJy 
  frequency = 110.25 #MHz
  error = false
  ref = "https://doi.org/10.1051/0004-6361/202449762"

[Width]

    [Width.110]
  value = 16 #ms
  frequency = 110.25 #MHz
  error = false
  ref = "https://doi.org/10.1051/0004-6361/202449762"

#Tyul'bashev et al. 2024: https://doi.org/10.1051/0004-6361/202449762